# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from hiddenswitch_comfy.api.paths.object_info.get.operation import ApiForGet


class ObjectInfo(
    ApiForGet,
):
    pass
