# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from hiddenswitch_comfy.api.paths.upload_image.post.operation import ApiForPost


class UploadImage(
    ApiForPost,
):
    pass
